package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Event implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "EventCategory")
	private String eventCategory;
	@org.kie.api.definition.type.Label(value = "EventSource")
	private String eventSource;
	@org.kie.api.definition.type.Label(value = "EventDate")
	private java.util.Date eventDate;
	@org.kie.api.definition.type.Label(value = "eventId")
	private String eventId;
	@org.kie.api.definition.type.Label(value = "EventValue")
	private String eventValue;

	public Event() {
	}

	public String getEventCategory() {
		return this.eventCategory;
	}

	public void setEventCategory(String eventCategory) {
		this.eventCategory = eventCategory;
	}

	public String getEventSource() {
		return this.eventSource;
	}

	public void setEventSource(String eventSource) {
		this.eventSource = eventSource;
	}

	public java.util.Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(java.util.Date eventDate) {
		this.eventDate = eventDate;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public String getEventValue() {
		return this.eventValue;
	}

	public void setEventValue(String eventValue) {
		this.eventValue = eventValue;
	}

	public Event(String eventCategory, String eventSource,
			java.util.Date eventDate, String eventId,
			String eventValue) {
		this.eventCategory = eventCategory;
		this.eventSource = eventSource;
		this.eventDate = eventDate;
		this.eventId = eventId;
		this.eventValue = eventValue;
	}

}