package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrainingModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ModelName")
	private String modelName;
	@org.kie.api.definition.type.Label(value = "Confidence")
	private Integer confidence;

	public TrainingModel() {
	}

	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public Integer getConfidence() {
		return this.confidence;
	}

	public void setConfidence(Integer confidence) {
		this.confidence = confidence;
	}

	public TrainingModel(String modelName,
			Integer confidence) {
		this.modelName = modelName;
		this.confidence = confidence;
	}

}